import { Card, ShellPage, Skel, TableShell } from "./common";
export function TodayShell(){return <ShellPage title="Today"><div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><Card className="min-h-48"><Skel className="h-20"/></Card><Card><Skel className="h-20"/></Card></div><div className="mt-4 grid gap-4 md:grid-cols-3"><Card/><Card/><Card/></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Card><TableShell rows={5} cols={2}/></Card><Card><TableShell rows={5} cols={3}/></Card><Card><TableShell rows={4} cols={3}/></Card><Card><TableShell rows={6} cols={2}/></Card></div></ShellPage>}
export function MarketsShell(){return <ShellPage title="Markets"><Card><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{Array.from({length:5}).map((_,i)=><Skel key={i} className="h-28"/>)}</div></Card><Card className="mt-4"><div className="mb-4 flex gap-2"><Skel className="h-9 w-28"/><Skel className="h-9 w-28"/><Skel className="h-9 w-28"/></div><Skel className="h-80"/></Card><div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Card><TableShell rows={5} cols={2}/></Card><Card><TableShell rows={6} cols={2}/></Card><Card><TableShell rows={8} cols={2}/></Card></div></ShellPage>}
export function TopNewsListShell(){return <ShellPage title="Top News"><Skel className="mb-4 h-9 w-24"/><Card><TableShell rows={8} cols={1}/></Card></ShellPage>}
export function ArticleDetailShell(){return <ShellPage title=""><Skel className="mb-5 h-9 w-24"/><article className="mx-auto max-w-3xl"><Skel className="h-12 w-11/12"/><Skel className="mt-4 h-4 w-64"/><Skel className="mt-4 h-6 w-52"/><div className="mt-8 space-y-4">{Array.from({length:8}).map((_,i)=><Skel key={i} className="h-5 w-full"/>)}</div></article></ShellPage>}
export function NewsCalendarShell(){return <ShellPage title="News & Calendar"><div className="grid gap-4 xl:grid-cols-3"><Card><TableShell rows={6} cols={1}/></Card><Card><TableShell rows={6} cols={3}/></Card><Card><TableShell rows={6} cols={3}/></Card></div></ShellPage>}
export function NewsListShell(){return <ShellPage title="Market News"><Card><TableShell rows={10} cols={2}/></Card></ShellPage>}
export function EarningsListShell(){return <ShellPage title="Earnings"><Card><TableShell rows={10} cols={5}/></Card></ShellPage>}
export function FlowShell(){return <ShellPage title="Flow"><div className="grid gap-4 md:grid-cols-3"><Card/><Card/><Card/></div><div className="mt-4 grid gap-4 xl:grid-cols-3"><Card><TableShell rows={6} cols={4}/></Card><Card><TableShell rows={6} cols={4}/></Card><Card><TableShell rows={6} cols={4}/></Card></div></ShellPage>}
export function OwnershipShell(){return <ShellPage title="Ownership"><div className="grid gap-4 xl:grid-cols-3"><Card/><Card><TableShell rows={6} cols={4}/></Card><Card><TableShell rows={6} cols={4}/></Card></div></ShellPage>}
export function InstitutionDetailShell(){return <ShellPage title="Institution"><div className="grid gap-4 md:grid-cols-4"><Card/><Card/><Card/><Card/></div><Card className="mt-4"><div className="mb-4 flex gap-2"><Skel className="h-8 w-32"/><Skel className="h-8 w-32"/><Skel className="h-8 w-32"/></div><TableShell rows={10} cols={6}/></Card></ShellPage>}
export function EconomyShell(){return <ShellPage title="Economy"><div className="grid gap-4 md:grid-cols-3"><Card/><Card/><Card/></div><Card className="mt-4"><div className="mb-4 flex gap-2"><Skel className="h-8 w-24"/><Skel className="h-8 w-24"/></div><div className="grid gap-4 lg:grid-cols-[0.8fr_1.2fr]"><TableShell rows={6} cols={2}/><Skel className="h-80"/></div></Card></ShellPage>}
export function SentimentShell(){return <ShellPage title="Sentiment"><div className="grid gap-4 md:grid-cols-3"><Card/><Card/><Card/></div><Card className="mt-4"><Skel className="h-80"/></Card></ShellPage>}
export function StatusShell(){return <ShellPage title="Status"><Card><TableShell rows={12} cols={5}/></Card></ShellPage>}
export function GenericShell(){return <ShellPage title="AlphaDigest"><div className="grid gap-4 md:grid-cols-3"><Card/><Card/><Card/></div><Card className="mt-4"><TableShell/></Card></ShellPage>}
