import assert from "node:assert/strict";
import test from "node:test";
import { calculateMarketWatchFromCandles } from "../lib/data/market-watch-candles";
import type { DailyCandle } from "../lib/data/daily-candles";
const row=(symbol:string,i:number,close=100):DailyCandle=>({symbol,providerSymbol:symbol,tradingDate:new Date(Date.UTC(2024,0,1+i)).toISOString().slice(0,10),open:close,high:close+1,low:close-1,close,volume:null,previousClose:null,source:"test",sourceTimestamp:null,fetchedAt:"now"});
function series(symbol:string,n:number,close=(i:number)=>100){return Array.from({length:n},(_,i)=>row(symbol,i,close(i)));}
test("52W highs/lows exclude latest benchmark and include equals/exceeds/falls",()=>{const a=series("AAA",253,()=>100); a[252]={...a[252],high:101,low:99,close:100}; const b=series("BBB",253,()=>100); b[252]={...b[252],high:102,low:98,close:100}; const c=series("CCC",253,()=>100); c[252]={...c[252],high:99,low:99.5,close:100}; const r=calculateMarketWatchFromCandles([...a,...b,...c],["AAA","BBB","CCC"]); assert.deepEqual(r.highs52Week.items.map(i=>i.symbol),["BBB","AAA"]); assert.deepEqual(r.lows52Week.items.map(i=>i.symbol),["BBB","AAA"]);});
test("200D crosses above below at and not proximity",()=>{const up=series("UP",201,i=>i<200?100:101); up[199]={...up[199],close:99}; const down=series("DOWN",201,i=>i<200?100:99); down[199]={...down[199],close:101}; const at=series("AT",201,()=>100); const stay=series("STAY",201,i=>i<200?110:111); const r=calculateMarketWatchFromCandles([...up,...down,...at,...stay],["UP","DOWN","AT","STAY"]); const sig=Object.fromEntries(r.crosses200Day.items.map(i=>[i.symbol,i.signal])); assert.equal(sig.UP,"crossed_above"); assert.equal(sig.DOWN,"crossed_below"); assert.equal(sig.AT,"at"); assert.equal(sig.STAY,undefined);});
test("200W requires 201 weekly closes and reports insufficient history",()=>{const short=series("SHORT",300,()=>100); const r=calculateMarketWatchFromCandles(short,["SHORT"]); assert.equal(r.crosses200Week.available,false); assert.match(r.crosses200Week.reason??"",/Insufficient history/);});
test("stale and invalid candles are excluded; row limit stable sort",()=>{let rows:DailyCandle[]=[]; for(let s=0;s<8;s++){const sym=`S${s}`; const a=series(sym,253,()=>100); a[252]={...a[252],high:110+s,close:100}; rows=rows.concat(a);} const stale=series("OLD",252,()=>100); rows=rows.concat(stale,{...row("BAD",252,100),high:1,low:2}); const r=calculateMarketWatchFromCandles(rows,[...Array.from({length:8},(_,i)=>`S${i}`),"OLD","BAD"]); assert.equal(r.highs52Week.items.length,5); assert.ok(r.coverage.staleSymbols.includes("OLD")); assert.equal(r.highs52Week.items[0].symbol,"S7");});
