import { dailyCandleEnvironmentSummary } from "../../lib/data/daily-candle-refresh";
import { finishJobRun, recordJobRun, startJobRun } from "../../lib/status/job-runs";
export const config = { schedule: "30 22,23 * * 1-5" };
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{"content-type":"application/json"}});
function torontoParts(now=new Date()){ const parts=Object.fromEntries(new Intl.DateTimeFormat("en-US",{timeZone:"America/Toronto",weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(now).map(p=>[p.type,p.value])); return {label:`${parts.year}-${parts.month}-${parts.day} ${parts.hour}:${parts.minute} America/Toronto`, weekday:parts.weekday, hour:Number(parts.hour), minute:Number(parts.minute)}; }
function shouldDispatch(now=new Date()){ const t=torontoParts(now); const utc=now.toISOString(); const weekday=["Mon","Tue","Wed","Thu","Fri"].includes(t.weekday); if(!weekday) return {shouldRun:false,reason:"not_toronto_weekday",utcTime:utc,torontoTime:t.label}; if(t.hour!==18||t.minute!==30) return {shouldRun:false,reason:"outside_1830_toronto_window",utcTime:utc,torontoTime:t.label}; return {shouldRun:true,reason:"scheduled_1830_toronto_window",utcTime:utc,torontoTime:t.label}; }
async function invokeWorker(correlationId:string, manual=false){ const site=process.env.URL || process.env.DEPLOY_URL; const workerPath="/.netlify/functions/refresh-daily-market-candles-worker-background"; const workerUrl=site?new URL(workerPath,site).toString():workerPath; console.info("daily_candle_worker_invocation_started",{correlationId,workerUrl,functionName:"refresh-daily-market-candles-worker-background",manual}); const res=await fetch(workerUrl,{method:"POST",headers:{"content-type":"application/json","x-alphadigest-worker-token":process.env.DAILY_CANDLE_WORKER_TOKEN || ""},body:JSON.stringify({correlationId,trigger:"dispatcher",manual})}); console.info("daily_candle_worker_invoked",{correlationId,workerUrl,status:res.status,ok:res.ok}); if(!res.ok) throw new Error(`Worker invocation failed with HTTP ${res.status}`); return {workerUrl,status:res.status}; }
export default async function handler(){ const startedAt=new Date().toISOString(); const correlationId=crypto.randomUUID(); const decision=shouldDispatch(); console.info("daily_candle_dispatch_started",{correlationId,startedAt,...decision,environment:dailyCandleEnvironmentSummary()}); if(!decision.shouldRun){ console.warn("daily_candle_dispatch_skipped",{correlationId,startedAt,...decision}); await recordJobRun({jobName:"Daily Market Candles",functionName:"refresh-daily-market-candles",source:"Finnhub",status:"skipped",startedAt,metadata:{correlationId,executionMode:"dispatcher",...decision}}); return json({ok:true,skipped:true,correlationId,decision}); } const run=await startJobRun({jobName:"Daily Market Candles",functionName:"refresh-daily-market-candles",source:"Finnhub",metadata:{correlationId,executionMode:"dispatcher",triggeredAt:startedAt,...decision} as any}); try{ const invocation=await invokeWorker(correlationId); await finishJobRun(run,{status:"success",metadata:{correlationId,executionMode:"dispatcher",workerInvocation:invocation,triggeredAt:startedAt}}); return json({ok:true,correlationId,workerInvocation:invocation}); }catch(e){ const msg=(e as Error).message; console.error("daily_candle_worker_invocation_failed",{correlationId,error:msg}); await finishJobRun(run,{status:"error",errorMessage:msg,metadata:{correlationId,executionMode:"dispatcher"} as any}); return json({ok:false,correlationId,error:msg},500); }}
export { shouldDispatch };
