import { DataTable } from "@/components/ui/data-table";
import { InfoTooltip } from "@/components/ui/info-tooltip";
import { PageTitle } from "@/components/ui/page-title";
import { Panel } from "@/components/ui/panel";
import { SectionHeader } from "@/components/ui/section-header";

const dark = [{ time: "10:12", ticker: "MSFT", price: "$468.20", size: "420K", notional: "$196.6M", venue: "TRF" }];
const whale = [{ time: "10:45", ticker: "NVDA", type: "Call sweep", premium: "$2.4M", side: "Bullish", expiry: "2026-07-17", strike: "$150" }];
const insider = [{ date: "2026-06-04", ticker: "ABC", insider: "CFO", role: "Officer", side: "Buy", value: "$1.2M", type: "Open market" }];
const congress = [{ published: "2026-06-03", traded: "2026-05-18", politician: "Member", ticker: "AAPL", side: "Buy", amount: "$15K-$50K", filed: "16 days" }];
const holdings = [{ fund: "Example Capital", ticker: "META", shares: "1.2M", value: "$755M", weight: "4.8%", change: "+18%", period: "Q1 2026", filed: "2026-05-15" }];
export default function FlowOwnershipPage() {
  return <><PageTitle title="Flow & Ownership" subtitle="Where big money is moving across short-term flow and slower ownership disclosures." /><Panel><SectionHeader title="Big Money Flow Summary" eyebrow="Trailing 7D by default" action={<div className="rounded-lg border border-border p-1 text-xs"><span className="rounded bg-accent/20 px-2 py-1 text-accent">7D</span><span className="px-2 py-1 text-mutedText">30D</span></div>} /><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6 text-sm"><p>Most active: <b>NVDA</b></p><p>Largest dark pool: <b>MSFT</b></p><p>Whale premium: <b>$2.4M</b></p><p>Whale flow: <b className="text-positive">Bullish</b></p><p>Insider buying: <b>ABC</b></p><p className="flex gap-1">13F: latest quarter <InfoTooltip label="13F filing" text="13F filings are quarterly and delayed, so they indicate institutional positioning rather than live trading flow." /></p></div></Panel><div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel><SectionHeader title="Dark Pool" /><DataTable columns={[{ key: "time", header: "Time" }, { key: "ticker", header: "Ticker" }, { key: "price", header: "Price", align: "right" }, { key: "size", header: "Size", align: "right" }, { key: "notional", header: "Notional", align: "right" }, { key: "venue", header: "Venue" }]} rows={dark} /></Panel><Panel><SectionHeader title="Whale Trades" /><DataTable columns={[{ key: "time", header: "Time" }, { key: "ticker", header: "Ticker" }, { key: "type", header: "Type" }, { key: "premium", header: "Premium", align: "right" }, { key: "side", header: "Side" }, { key: "expiry", header: "Expiry" }, { key: "strike", header: "Strike", align: "right" }]} rows={whale} /></Panel><Panel><SectionHeader title="Insider Trades" /><DataTable columns={[{ key: "date", header: "Date" }, { key: "ticker", header: "Ticker" }, { key: "insider", header: "Insider" }, { key: "role", header: "Role" }, { key: "side", header: "Side" }, { key: "value", header: "Value", align: "right" }, { key: "type", header: "Type" }]} rows={insider} /></Panel><Panel><SectionHeader title="Congressional Trades" /><DataTable columns={[{ key: "published", header: "Published" }, { key: "traded", header: "Traded" }, { key: "politician", header: "Politician" }, { key: "ticker", header: "Ticker" }, { key: "side", header: "Side" }, { key: "amount", header: "Amount" }, { key: "filed", header: "Filed after" }]} rows={congress} /></Panel></div><Panel className="mt-4"><SectionHeader title="Institutional Positioning" eyebrow="Latest 13F data, not live trading flow" /><DataTable columns={[{ key: "fund", header: "Fund" }, { key: "ticker", header: "Ticker" }, { key: "shares", header: "Shares", align: "right" }, { key: "value", header: "Market value", align: "right" }, { key: "weight", header: "Weight", align: "right" }, { key: "change", header: "QoQ", align: "right" }, { key: "period", header: "Period" }, { key: "filed", header: "Filed" }]} rows={holdings} /></Panel></>;
}
