import { cn } from "@/lib/utils/cn";
function Block({ className }: { className?: string }) { return <div className={cn("animate-pulse rounded-sm bg-panelHover/80", className)} />; }
export function ValueSkeleton({ className }: { className?: string }) { return <Block className={cn("h-5 w-20", className)} />; }
export function ChartSkeleton({ className }: { className?: string }) { return <Block className={cn("h-72 w-full", className)} />; }
export function TableSkeleton({ rows = 6 }: { rows?: number }) { return <div className="space-y-3">{Array.from({length:rows}).map((_,i)=><Block key={i} className="h-8 w-full" />)}</div>; }
export function PanelSkeleton({ children, className }: { children?: React.ReactNode; className?: string }) { return <section className={cn("rounded-none border border-borderStrong bg-panel p-4 shadow-panel", className)} aria-busy="true"><Block className="mb-4 h-5 w-44" />{children ?? <Block className="h-28" />}</section>; }
export function DashboardLoadingSkeleton({ title = "Loading dashboard" }: { title?: string; table?: boolean }) { return <div role="status" aria-live="polite" aria-busy="true"><span className="sr-only">{title}</span><Block className="mb-5 h-8 w-64"/><div className="grid gap-4 md:grid-cols-3"><Block className="h-28"/><Block className="h-28"/><Block className="h-28"/></div><div className="mt-4 space-y-4"><PanelSkeleton><TableSkeleton /></PanelSkeleton><PanelSkeleton /></div></div>; }
export function MarketsLoadingShell() { return <div role="status" aria-live="polite" aria-busy="true"><span className="sr-only">Loading Markets data</span><Block className="mb-5 h-8 w-40"/><PanelSkeleton><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{Array.from({length:5}).map((_,i)=><Block key={i} className="h-28" />)}</div></PanelSkeleton><PanelSkeleton className="mt-4"><Block className="h-96" /></PanelSkeleton><div className="mt-4 grid gap-4 xl:grid-cols-3"><PanelSkeleton><TableSkeleton rows={5}/></PanelSkeleton><PanelSkeleton><div className="space-y-3"><Block className="h-28"/><Block className="h-28"/></div></PanelSkeleton><PanelSkeleton><div className="space-y-3"><Block className="h-20"/><Block className="h-20"/><Block className="h-20"/><Block className="h-20"/></div></PanelSkeleton></div></div>; }
export function EconomyLoadingShell() { return <div role="status" aria-live="polite" aria-busy="true"><span className="sr-only">Loading Economy data</span><Block className="mb-5 h-8 w-40"/><div className="grid gap-4 md:grid-cols-3">{Array.from({length:3}).map((_,i)=><Block key={i} className="h-32" />)}</div><PanelSkeleton className="mt-4"><Block className="mb-4 h-10 w-full"/><div className="grid gap-4 lg:grid-cols-[320px_1fr]"><Block className="h-80"/><ChartSkeleton /></div></PanelSkeleton></div>; }
export function OwnershipLoadingShell() { return <div role="status" aria-live="polite" aria-busy="true"><span className="sr-only">Loading Ownership data</span><Block className="mb-5 h-8 w-44"/><div className="grid gap-4 lg:grid-cols-3"><PanelSkeleton/><PanelSkeleton/><PanelSkeleton/></div><PanelSkeleton className="mt-4"><TableSkeleton rows={8}/></PanelSkeleton></div>; }
