import { todayMock } from "@/lib/data/fixtures/mock-dashboard";
import { PageTitle } from "@/components/dashboard/page-title";
import { Panel } from "@/components/ui/panel";
import { SectionHeader } from "@/components/ui/section-header";
import { MetricRow } from "@/components/ui/metric-row";
import { SourceFooter } from "@/components/ui/source-footer";
import { DataTable } from "@/components/ui/data-table";

export function TodayView() {
  return <><PageTitle title="Today" subtitle="What matters today across backdrop, tape, catalysts, and risk." /><div className="grid gap-4 xl:grid-cols-[1fr_360px]"><Panel><SectionHeader title="Market Summary" subtitle={todayMock.summary.regime} info="VIX3M/VIX compares 3-month implied volatility with 30-day implied volatility. A compressed ratio can suggest near-term stress." /><h2 className="text-xl font-semibold">{todayMock.summary.title}</h2><ul className="mt-4 grid gap-2 text-sm text-textSecondary">{todayMock.summary.bullets.map((b) => <li key={b} className="rounded-xl border border-borderStrong bg-sidebar p-3">{b}</li>)}</ul><SourceFooter meta={todayMock.sourceMeta} /></Panel><Panel><SectionHeader title="Key Market Stats" subtitle="Compact cross-asset watchlist" />{todayMock.keyStats.map((m) => <MetricRow key={m.label} metric={m} />)}</Panel></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Panel><SectionHeader title="Today's Top News" subtitle="Featured news from Unusual Whales only" />{todayMock.featuredNews.map((n) => <div key={n.headline} className="border-b border-borderStrong py-3 last:border-b-0"><p className="text-sm font-medium">{n.headline}</p><p className="mt-1 text-xs text-textMuted">{n.timestamp} • {n.source} • {n.tickers.join(", ")}</p><p className="mt-1 text-xs text-textSecondary">{n.whyItMatters}</p></div>)}</Panel><Panel><SectionHeader title="Today’s Earnings & Economic Calendar" /><div className="grid gap-4"><DataTable rows={todayMock.earnings.map((e) => ({ Ticker: e.ticker, Company: e.company, Time: e.time, EPS: e.expectedEps, Revenue: e.expectedRevenue ?? "—" }))} /><DataTable rows={todayMock.economicCalendar.map((e) => ({ Time: e.time, Event: e.event, Actual: e.actual ?? "—", Forecast: e.forecast ?? "—", Previous: e.previous ?? "—", Importance: e.importance }))} /></div></Panel></div><Panel className="mt-4"><SectionHeader title="Sector Performance Snapshot" subtitle="MVP sector ETF universe until true flow methodology is available" />{todayMock.sectorSnapshot.map((m) => <MetricRow key={m.label} metric={m} />)}</Panel></>;
}
