import { MiniChart } from "@/components/ui/mini-chart";
import { PageTitle } from "@/components/ui/page-title";
import { Panel } from "@/components/ui/panel";
import { SectionHeader } from "@/components/ui/section-header";
import { MetricRow } from "@/components/ui/metric-row";

export default function TickerPage({ params }: { params: { symbol: string } }) {
  const symbol = params.symbol.toUpperCase();
  return <><PageTitle title={`${symbol} Ticker Detail`} subtitle="Ticker-level price, story, event timeline, flow, ownership, and sector context with partial-data fallback." /><Panel><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs text-mutedText">Example Company Inc.</p><h2 className="text-3xl font-semibold">{symbol}</h2><p className="text-sm text-secondaryText">Technology · Market cap $3.1T · Updated 1:35 PM ET</p></div><div className="text-right"><p className="text-2xl font-semibold tabular-nums">$204.18</p><p className="text-positive tabular-nums">+$2.44 +1.21%</p></div></div></Panel><div className="mt-4 grid gap-4 xl:grid-cols-[1.3fr_0.7fr]"><Panel><SectionHeader title="Price / OHLC Chart" eyebrow="1D · 5D · 1M · 3M · 1Y" /><MiniChart /></Panel><Panel><SectionHeader title="Today's Story" /><p className="text-sm leading-6 text-secondaryText">{symbol} is trading higher in mock mode with constructive sector context, limited stale flow data, and no confirmed live ownership update. Add API keys and scheduled caches to enable live modules.</p></Panel></div><div className="mt-4 grid gap-4 xl:grid-cols-3"><Panel><SectionHeader title="Event Timeline" /><MetricRow metric={{ label: "News", value: "3 items", change: "mock" }} /><MetricRow metric={{ label: "Earnings", value: "Next quarter", change: "cached" }} /></Panel><Panel><SectionHeader title="Flow Snapshot" /><MetricRow metric={{ label: "Dark pool", value: "Unavailable", change: "stale" }} /><MetricRow metric={{ label: "Whale trades", value: "2 mock", change: "cached" }} /></Panel><Panel><SectionHeader title="Ownership Snapshot" /><MetricRow metric={{ label: "13F QoQ", value: "+4.2%", change: "latest quarter" }} /><MetricRow metric={{ label: "Congress", value: "No recent mock", change: "delayed" }} /></Panel></div></>;
}
