import { InfoTooltip } from "@/components/ui/info-tooltip";
import { PageTitle } from "@/components/ui/page-title";
import { Panel } from "@/components/ui/panel";
import { SectionHeader } from "@/components/ui/section-header";
import { MetricRow } from "@/components/ui/metric-row";
import { keyMarketStats } from "@/lib/data/fixtures/market";

const badges = ["Macro: Neutral", "Rates: Restrictive", "Inflation: Cooling", "Labor: Softening", "Credit: Stable", "Sentiment: Bearish", "Oil: Rising"];
export default function EconomySentimentPage() {
  return <><PageTitle title="Economy & Sentiment" subtitle="Macro and sentiment backdrop across rates, inflation, labor, oil, credit, liquidity, and positioning." /><Panel><SectionHeader title="Macro Regime Summary" /><div className="flex flex-wrap gap-2">{badges.map((badge) => <span key={badge} className="rounded-full border border-border bg-sidebar px-3 py-1 text-xs text-secondaryText">{badge}</span>)}</div></Panel><div className="mt-4 grid gap-4 xl:grid-cols-3"><Panel><SectionHeader title="Rates & Yield Curve" /><MetricRow metric={{ label: "Fed policy rate", value: "5.25%-5.50%", change: "0 bp" }} /><MetricRow metric={{ label: "2Y yield", value: "4.74%", change: "+2 bp" }} /><MetricRow metric={{ label: "10Y-2Y spread", value: "-43 bp", change: "+1 bp" }} /></Panel><Panel><SectionHeader title="Inflation" /><MetricRow metric={{ label: "CPI YoY", value: "3.3%", change: "-0.1" }} /><MetricRow metric={{ label: "Core CPI YoY", value: "3.4%", change: "-0.2" }} /><MetricRow metric={{ label: "PPI YoY", value: "2.2%", change: "+0.1" }} /></Panel><Panel><SectionHeader title="Labor Market" /><MetricRow metric={{ label: "Unemployment", value: "4.0%", change: "+0.1" }} /><MetricRow metric={{ label: "Initial claims", value: "229K", change: "+4K" }} /><MetricRow metric={{ label: "Continuing claims", value: "1.86M", change: "+12K" }} /></Panel><Panel><SectionHeader title="Sentiment & Positioning" /><MetricRow metric={{ label: "CBOE total put/call", value: "0.86", change: "-0.05" }} /><MetricRow metric={{ label: "AAII bullish", value: "39.2%", change: "+2.1" }} /><p className="mt-3 flex items-center gap-1 text-xs text-mutedText">Put/call ratio <InfoTooltip label="Put/call ratio" text="A put/call ratio compares put option volume with call option volume and is often used as a sentiment gauge." /></p></Panel><Panel><SectionHeader title="Oil & Geopolitical Risk" /><MetricRow metric={keyMarketStats[3]} /><MetricRow metric={{ label: "Brent crude oil", value: "$77.24", change: "+$0.47", changePercent: "+0.61%" }} /><p className="mt-3 text-xs text-mutedText">Oil prices are expected from Finnhub, Twelve Data, FRED where appropriate, or another available provider. HormuzTracker is optional and attribution-aware.</p></Panel><Panel><SectionHeader title="Liquidity / Fed Plumbing" /><MetricRow metric={{ label: "Reverse repo", value: "$412B", change: "-$18B" }} /><MetricRow metric={{ label: "SOFR", value: "5.32%", change: "0 bp" }} /><MetricRow metric={{ label: "Fed balance sheet", value: "$7.3T", change: "-$12B" }} /></Panel></div></>;
}
