import { DataTable } from "@/components/ui/data-table";
import { InfoTooltip } from "@/components/ui/info-tooltip";
import { MiniChart } from "@/components/ui/mini-chart";
import { Panel } from "@/components/ui/panel";
import { SectionHeader } from "@/components/ui/section-header";
import { describeCommodityProvider } from "@/lib/data/adapters/commodity-prices-adapter";

export default function EconomySentimentPage() {
  const wti = describeCommodityProvider("WTI");
  const brent = describeCommodityProvider("BRENT");
  return <div className="space-y-4"><div><h1 className="text-2xl font-semibold">Is the broader backdrop supportive or risky?</h1><p className="text-sm text-mutedText">Macro, sentiment, oil, and liquidity view with FRED-first official time series.</p></div><Panel><SectionHeader title="Macro Regime Summary"/><div className="flex flex-wrap gap-2">{["Macro: Neutral","Rates: Restrictive","Inflation: Cooling","Labor: Softening","Credit: Stable","Sentiment: Bearish","Oil: Rising"].map(x=><span key={x} className="rounded-full border border-border bg-sidebar/50 px-3 py-1 text-xs text-secondaryText">{x}</span>)}</div></Panel><div className="grid gap-4 xl:grid-cols-2"><Panel><SectionHeader title="Rates & Yield Curve" subtitle="Fed policy rate, 2Y, 10Y, spreads, HY/IG spreads."/><MiniChart label="FRED rates and yield curve chart"/></Panel><Panel><SectionHeader title="Inflation" subtitle="CPI YoY, Core CPI YoY, CPI MoM, PPI YoY, PPI MoM."/><MiniChart label="FRED inflation chart"/></Panel><Panel><SectionHeader title="Labor Market" subtitle="Unemployment, initial claims, continuing claims."/><MiniChart label="FRED labor chart"/></Panel><Panel><SectionHeader title="Sentiment & Positioning" subtitle="CBOE put/call and AAII investor sentiment."/><DataTable columns={[{key:"metric",label:"Metric"},{key:"value",label:"Value",align:"right"},{key:"source",label:"Source"}]} rows={[{metric:"CBOE total put/call",value:"0.89",source:"CBOE"},{metric:"AAII bullish",value:"36%",source:"AAII"},{metric:"AAII bull-bear spread",value:"-4%",source:"AAII"}]}/><p className="mt-2 text-xs text-mutedText">Put/call ratio <InfoTooltip label="The put/call ratio compares put option volume with call option volume and is often used as a contrarian sentiment gauge." /></p></Panel><Panel><SectionHeader title="Oil & Geopolitical Risk" subtitle="WTI and Brent use Finnhub, Twelve Data, FRED macro context, or another provider where appropriate."/><DataTable columns={[{key:"asset",label:"Asset"},{key:"provider",label:"Selected provider"},{key:"status",label:"Status"},{key:"message",label:"Message"}]} rows={[{asset:"WTI crude oil",provider:wti.selectedProvider,status:wti.status,message:wti.message},{asset:"Brent crude oil",provider:brent.selectedProvider,status:brent.status,message:brent.message},{asset:"Hormuz status",provider:"Optional HormuzTracker",status:"disabled",message:"Enable HORMUZ_TRACKER_ENABLED and include attribution."}]}/></Panel><Panel><SectionHeader title="Liquidity / Fed Plumbing" subtitle="Reverse repo, SOFR, Fed balance sheet, Treasury General Account."/><MiniChart label="FRED liquidity chart"/></Panel></div></div>;
}
