"use client";
import { useEffect, useState } from "react";
import { cn } from "@/lib/utils/cn";
import { TradingViewOhlcvChart, type ChartCandle } from "./tradingview-ohlcv-chart";
const ranges = ["1W","1M","3M","YTD","1Y"] as const;
type Range = typeof ranges[number];
type Candle = ChartCandle & { previousClose?:number|null };
type ApiPayload = { symbol:string; range:Range; table:string; available:boolean; candles:Candle[]; metadata:{ source:string|null; latestTradingDate:string|null; earliestTradingDate?:string|null; fetchedAt:string|null; rows:number; label:string; providerSymbol?:string|null; resolution?:string; marketCalendar?:"24/7"|"exchange"|"futures"; timezone?:string; dataVersion?:string|null } };
type ChartState = { loading:boolean; error?:string; notice?:string; payload?:ApiPayload };
function chartTitleParts(label:string, symbol:string) {
  const ticker = symbol.toUpperCase();
  return label.trim().toUpperCase() === ticker ? { name:null as string|null, ticker } : { name:label, ticker };
}
const realTables = new Set(["crypto_daily_candles","market_daily_candles","sp500_daily_candles"]);
function validPayload(j:any): ApiPayload | null { const p=j?.payload; if (!p || j.mode !== "cached" || p.available !== true || !Array.isArray(p.candles) || p.candles.length === 0 || !realTables.has(p.table)) return null; return p as ApiPayload; }
export function MarketChartModal({ symbol, label, onClose }: { symbol:string; label:string; onClose:()=>void }) {
  const [range,setRange]=useState<Range>("1W"); const [state,setState]=useState<ChartState>({loading:true});
  useEffect(()=>{ setRange("1W"); },[symbol]);
  useEffect(()=>{ const prev=document.body.style.overflow; document.body.style.overflow="hidden"; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape") onClose();}; window.addEventListener("keydown",onKey); return()=>{document.body.style.overflow=prev; window.removeEventListener("keydown",onKey);};},[onClose]);
  useEffect(()=>{ let cancelled=false; setState({loading:true}); fetch(`/api/markets/candles?symbol=${encodeURIComponent(symbol)}&range=${range}`, { cache:"no-store" }).then(async r=>{const j=await r.json().catch(()=>({})); if(!r.ok) throw new Error(j?.notices?.[0] ?? j?.error ?? "Candle request failed"); const p=validPayload(j); if (!p) { const notice = j?.notices?.[0] ?? "No cached candle history is available for this symbol."; return { notice }; } return { payload:p };}).then(result=>{ if(cancelled) return; if (result.payload) setState({loading:false,payload:result.payload}); else setState({loading:false,notice:result.notice});}).catch(e=>{ if(!cancelled) setState({loading:false,error:(e as Error).message});}); return()=>{cancelled=true};},[symbol,range]);
  const title = chartTitleParts(label, symbol); const accessibleTitle = [title.name, title.ticker].filter(Boolean).join(" ");
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-labelledby="market-chart-title" aria-label={`${accessibleTitle} candle chart`} className="flex h-[82vh] w-[94vw] max-w-[960px] flex-col border border-borderStrong bg-panel shadow-2xl md:h-[75vh] md:w-[80vw] lg:w-[64vw] xl:w-[60vw]" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3 border-b border-borderStrong bg-sidebar px-4 py-3"><div><h2 id="market-chart-title" className="flex flex-wrap items-baseline gap-x-2 text-sm font-bold tracking-[0.18em] text-textPrimary">{title.name ? <span>{title.name}</span> : null}<span className="uppercase text-textMuted">{title.ticker}</span></h2></div><button aria-label="Close chart" onClick={onClose} className="border border-borderStrong px-3 py-1 text-textSecondary hover:bg-panelHover hover:text-textPrimary">×</button></div><div className="flex flex-wrap items-center gap-2 border-b border-borderStrong p-2"><div className="inline-flex border border-borderStrong bg-sidebar/80 p-1">{ranges.map(r=><button key={r} onClick={()=>setRange(r)} className={cn("px-3 py-1 text-xs font-semibold", range===r?"bg-accentBlue text-white":"text-textSecondary hover:text-textPrimary")}>{r}</button>)}</div></div><div className="min-h-0 flex-1 p-3">{state.loading?<div role="status" aria-live="polite" aria-busy="true" className="h-full rounded-none border border-borderStrong bg-sidebar/60 p-3"><span className="sr-only">Loading candle chart</span><div className="mb-3 h-4 w-40 animate-pulse bg-panelHover"/><div className="h-[calc(100%-2rem)] animate-pulse bg-panelHover"/></div>:state.error?<div className="text-negative">{state.error}</div>:state.payload?.candles.length?<TradingViewOhlcvChart key={`${symbol}-${range}`} symbol={symbol} candles={state.payload.candles}/>:<div className="flex h-full items-center justify-center text-textMuted">{state.notice ?? "No cached candle history available."}</div>}</div></div></div>;
}
