"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { cn } from "@/lib/utils/cn";
const ranges = ["1D","1W","1M","3M","YTD","1Y"] as const;
type Range = typeof ranges[number];
export type Candle = { date:string; open:number; high:number; low:number; close:number; volume:number|null };
type ApiPayload = { symbol:string; range:Range; table:string; available:boolean; candles:Candle[]; metadata:{ source:string|null; latestTradingDate:string|null; earliestTradingDate?:string|null; fetchedAt:string|null; rows:number; label:string; providerSymbol?:string|null } };
type ChartState = { loading:boolean; error?:string; notice?:string; payload?:ApiPayload };
const realTables = new Set(["crypto_daily_candles","market_daily_candles","sp500_daily_candles"]);
function validPayload(j:any): ApiPayload | null { const p=j?.payload; if (!p || j.mode !== "cached" || p.available !== true || !Array.isArray(p.candles) || p.candles.length === 0 || !realTables.has(p.table)) return null; return p as ApiPayload; }
export function MarketChartModal({ symbol, label, onClose }: { symbol:string; label:string; onClose:()=>void }) {
  const [range,setRange]=useState<Range>("1D"); const [state,setState]=useState<ChartState>({loading:true}); const cache=useRef(new Map<string,ApiPayload>());
  useEffect(()=>{ const prev=document.body.style.overflow; document.body.style.overflow="hidden"; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape") onClose();}; window.addEventListener("keydown",onKey); return()=>{document.body.style.overflow=prev; window.removeEventListener("keydown",onKey);};},[onClose]);
  useEffect(()=>{ let cancelled=false; const key=`${symbol}:${range}`; const cached=cache.current.get(key); if(cached){setState({loading:false,payload:cached}); return;} setState({loading:true}); fetch(`/api/markets/candles?symbol=${encodeURIComponent(symbol)}&range=${range}`, { cache:"no-store" }).then(async r=>{const j=await r.json().catch(()=>({})); if(!r.ok) throw new Error(j?.notices?.[0] ?? j?.error ?? "Candle request failed"); const p=validPayload(j); if (!p) { const notice = j?.notices?.[0] ?? "No cached candle history is available for this symbol."; return { notice }; } return { payload:p };}).then(result=>{ if(cancelled) return; if (result.payload) { cache.current.set(key,result.payload); setState({loading:false,payload:result.payload}); } else setState({loading:false,notice:result.notice});}).catch(e=>{ if(!cancelled) setState({loading:false,error:(e as Error).message});}); return()=>{cancelled=true};},[symbol,range]);
  const source = state.payload?.metadata.source; const asOf = state.payload?.metadata.latestTradingDate; const rows = state.payload?.metadata.rows;
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-labelledby="market-chart-title" className="flex h-[82vh] w-[94vw] max-w-6xl flex-col border border-borderStrong bg-panel shadow-2xl md:h-[75vh] md:w-[75vw]" onMouseDown={e=>e.stopPropagation()}><div className="flex items-center justify-between border-b border-borderStrong bg-sidebar px-4 py-3"><div><h2 id="market-chart-title" className="text-sm font-bold uppercase tracking-[0.18em] text-textPrimary">{symbol} <span className="text-textMuted">{label}</span></h2><p className="text-xs text-textMuted">Real Supabase daily OHLC candles with volume{source ? ` · Source: ${source}` : ""}{asOf ? ` · As of: ${asOf}` : ""}{rows ? ` · Rows: ${rows}` : ""}</p></div><button aria-label="Close chart" onClick={onClose} className="border border-borderStrong px-3 py-1 text-textSecondary hover:bg-panelHover hover:text-textPrimary">×</button></div><div className="border-b border-borderStrong p-2"><div className="inline-flex border border-borderStrong bg-sidebar/80 p-1">{ranges.map(r=><button key={r} onClick={()=>setRange(r)} className={cn("px-3 py-1 text-xs font-semibold", range===r?"bg-accentBlue text-white":"text-textSecondary hover:text-textPrimary")}>{r}</button>)}</div></div><div className="min-h-0 flex-1 p-4">{state.loading?<div className="flex h-full items-center justify-center text-textMuted">Loading candles…</div>:state.error?<div className="text-negative">{state.error}</div>:state.payload?.candles.length?<Candles candles={state.payload.candles}/>:<div className="flex h-full items-center justify-center text-textMuted">{state.notice ?? "No cached candle history available."}</div>}</div></div></div>;
}
function Candles({candles}:{candles:Candle[]}){ const {min,max,maxVolume}=useMemo(()=>{const vals=candles.flatMap(c=>[c.high,c.low]); const vols=candles.map(c=>c.volume ?? 0).filter(v=>Number.isFinite(v)&&v>=0); return {min:Math.min(...vals),max:Math.max(...vals),maxVolume:Math.max(0,...vols)}},[candles]); const pad=(max-min)*0.08||1; const lo=min-pad, hi=max+pad; const w=900,h=420; const priceTop=20, priceBottom=315, volumeTop=335, volumeBottom=400; const x=(i:number)=> candles.length===1?w/2: 30+i*((w-60)/(candles.length-1)); const y=(v:number)=> priceTop+(hi-v)*((priceBottom-priceTop)/(hi-lo)); return <svg className="h-full w-full bg-[#07111f]" viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Candlestick price and volume chart"><line x1="30" x2="870" y1={y(max)} y2={y(max)} stroke="#243244"/><line x1="30" x2="870" y1={y(min)} y2={y(min)} stroke="#243244"/><line x1="30" x2="870" y1={volumeBottom} y2={volumeBottom} stroke="#243244"/>{candles.map((c,i)=>{const up=c.close>=c.open; const cx=x(i); const bw=Math.max(4, Math.min(14, 650/candles.length)); const color=up?"#22c55e":"#ef4444"; const volumeHeight=maxVolume>0&&c.volume!=null?Math.max(c.volume===0?0:1,(c.volume/maxVolume)*(volumeBottom-volumeTop)):0; return <g key={c.date}><line x1={cx} x2={cx} y1={y(c.high)} y2={y(c.low)} stroke={color}/><rect x={cx-bw/2} y={Math.min(y(c.open),y(c.close))} width={bw} height={Math.max(1,Math.abs(y(c.open)-y(c.close)))} fill={color}/>{c.volume!=null?<rect data-testid="volume-bar" x={cx-bw/2} y={volumeBottom-volumeHeight} width={bw} height={volumeHeight} fill={color} opacity="0.35"/>:null}</g>})}<text x="36" y="18" fill="#94a3b8" fontSize="11">{max.toFixed(2)}</text><text x="36" y={priceBottom-4} fill="#94a3b8" fontSize="11">{min.toFixed(2)}</text><text x="36" y={volumeTop-6} fill="#94a3b8" fontSize="11">Volume</text></svg> }
