"use client";
import { useEffect, useState } from "react";
import { cn } from "@/lib/utils/cn";
import { TradingViewOhlcvChart, type ChartCandle } from "./tradingview-ohlcv-chart";
const ranges = ["1D","1W","1M","3M","YTD","1Y"] as const;
type Range = typeof ranges[number];
type Candle = ChartCandle & { previousClose?:number|null };
type ApiPayload = { symbol:string; range:Range; table:string; available:boolean; candles:Candle[]; metadata:{ source:string|null; latestTradingDate:string|null; earliestTradingDate?:string|null; fetchedAt:string|null; rows:number; label:string; providerSymbol?:string|null; resolution?:string; marketCalendar?:"24/7"|"exchange"; timezone?:string; dataVersion?:string|null } };
type ChartState = { loading:boolean; error?:string; notice?:string; payload?:ApiPayload };
const realTables = new Set(["crypto_daily_candles","market_daily_candles","sp500_daily_candles"]);
function validPayload(j:any): ApiPayload | null { const p=j?.payload; if (!p || j.mode !== "cached" || p.available !== true || !Array.isArray(p.candles) || p.candles.length === 0 || !realTables.has(p.table)) return null; return p as ApiPayload; }
function prettyDate(s?:string|null){ return s ? new Date(`${s}T00:00:00Z`).toLocaleDateString(undefined,{year:"numeric",month:"short",day:"numeric",timeZone:"UTC"}) : null; }
export function MarketChartModal({ symbol, label, onClose }: { symbol:string; label:string; onClose:()=>void }) {
  const [range,setRange]=useState<Range>("1D"); const [state,setState]=useState<ChartState>({loading:true});
  useEffect(()=>{ setRange("1D"); },[symbol]);
  useEffect(()=>{ const prev=document.body.style.overflow; document.body.style.overflow="hidden"; const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape") onClose();}; window.addEventListener("keydown",onKey); return()=>{document.body.style.overflow=prev; window.removeEventListener("keydown",onKey);};},[onClose]);
  useEffect(()=>{ let cancelled=false; setState({loading:true}); fetch(`/api/markets/candles?symbol=${encodeURIComponent(symbol)}&range=${range}`, { cache:"no-store" }).then(async r=>{const j=await r.json().catch(()=>({})); if(!r.ok) throw new Error(j?.notices?.[0] ?? j?.error ?? "Candle request failed"); const p=validPayload(j); if (!p) { const notice = j?.notices?.[0] ?? "No cached candle history is available for this symbol."; return { notice }; } return { payload:p };}).then(result=>{ if(cancelled) return; if (result.payload) setState({loading:false,payload:result.payload}); else setState({loading:false,notice:result.notice});}).catch(e=>{ if(!cancelled) setState({loading:false,error:(e as Error).message});}); return()=>{cancelled=true};},[symbol,range]);
  const m = state.payload?.metadata; const sourceLine = m ? [`Source: ${m.source ?? "Supabase candles"}`, m.resolution?.toUpperCase() ?? "Daily", m.latestTradingDate ? `As of ${prettyDate(m.latestTradingDate)}` : null, `${m.rows} row${m.rows===1?"":"s"}`, m.marketCalendar ? `${m.marketCalendar} calendar` : null].filter(Boolean).join(" · ") : "Daily OHLCV candles from Supabase";
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-3" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-labelledby="market-chart-title" className="flex h-[82vh] w-[94vw] max-w-6xl flex-col border border-borderStrong bg-panel shadow-2xl md:h-[75vh] md:w-[75vw]" onMouseDown={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3 border-b border-borderStrong bg-sidebar px-4 py-3"><div><h2 id="market-chart-title" className="text-sm font-bold uppercase tracking-[0.18em] text-textPrimary">{symbol} <span className="text-textMuted">{label}</span></h2><p className="mt-1 text-xs text-textMuted">{sourceLine}</p></div><button aria-label="Close chart" onClick={onClose} className="border border-borderStrong px-3 py-1 text-textSecondary hover:bg-panelHover hover:text-textPrimary">×</button></div><div className="flex flex-wrap items-center justify-between gap-2 border-b border-borderStrong p-2"><div className="inline-flex border border-borderStrong bg-sidebar/80 p-1">{ranges.map(r=><button key={r} onClick={()=>setRange(r)} className={cn("px-3 py-1 text-xs font-semibold", range===r?"bg-accentBlue text-white":"text-textSecondary hover:text-textPrimary")}>{r}</button>)}</div><span className="text-[11px] text-textMuted">1D currently uses daily bars until intraday storage is available.</span></div><div className="min-h-0 flex-1 p-3">{state.loading?<div className="flex h-full items-center justify-center text-textMuted">Loading candles…</div>:state.error?<div className="text-negative">{state.error}</div>:state.payload?.candles.length?<TradingViewOhlcvChart key={`${symbol}-${range}`} symbol={symbol} candles={state.payload.candles}/>:<div className="flex h-full items-center justify-center text-textMuted">{state.notice ?? "No cached candle history available."}</div>}</div></div></div>;
}
