/** TEMPORARY: one-time Unusual Whales stock/market candle backfill. Remove after production validation. */
import { getSp500CandleUniverse, normalizeUnusualWhalesCandles, upsertDailyCandles } from "../lib/data/daily-candles";
import { marketCandleAssets } from "../lib/data/market-assets";

const args = new Map(process.argv.slice(2).map((arg, i, arr) => arg.startsWith("--") ? [arg, arr[i+1] && !arr[i+1].startsWith("--") ? arr[i+1] : "true"] : ["",""]));
const group = args.get("--group") ?? "all"; const start = Number(args.get("--start-index") ?? 0); const limit = Number(args.get("--limit") ?? Number.POSITIVE_INFINITY); const force = args.has("--force");
if (process.env.ENABLE_UW_CANDLE_BACKFILL !== "true") { console.error("Set ENABLE_UW_CANDLE_BACKFILL=true to run the temporary UW stock/market backfill."); process.exit(1); }
const token = process.env.UNUSUAL_WHALES_API_KEY; if (!token) throw new Error("UNUSUAL_WHALES_API_KEY missing");
async function fetchUw(symbol:string){ const url=`https://phx.unusualwhales.com/api/ticker_candles/${encodeURIComponent(symbol)}/historic/v2?interval=1y&include_1m_data=true`; const res=await fetch(url,{cache:"no-store",headers:{Authorization:`Bearer ${token}`,accept:"application/json"}}); if(!res.ok) throw new Error(`UW ${res.status}`); return res.json(); }
async function main(){ const sp500 = group === "markets" ? [] : (await getSp500CandleUniverse()).map(symbol=>({table:"sp500_daily_candles" as const, symbol, providerSymbol:symbol.replace(/-/g,".")})); const markets = group === "sp500" ? [] : marketCandleAssets.filter(a=>a.chartAvailable && a.unusualWhalesSymbol).map(a=>({table:"market_daily_candles" as const, symbol:a.symbol, providerSymbol:a.unusualWhalesSymbol!, assetGroup:a.group})); const jobs=[...sp500,...markets].slice(start, start+limit); const results=[]; for (const job of jobs){ try{ const payload=await fetchUw(job.providerSymbol); const candles=normalizeUnusualWhalesCandles(job.symbol, job.providerSymbol, payload); candles.forEach(c=>(c.assetGroup=(job as any).assetGroup)); const up=await upsertDailyCandles(job.table,candles); const dates=candles.map(c=>c.tradingDate).sort(); results.push({symbol:job.symbol, ok:true, rows:up.upserted, earliest:dates[0]??null, latest:dates.at(-1)??null, force}); console.log(results.at(-1)); }catch(e){ results.push({symbol:job.symbol, ok:false, error:(e as Error).message}); console.error(results.at(-1)); }} const failed=results.filter(r=>!r.ok).length; console.log(JSON.stringify({processed:results.length, failed, results},null,2)); if(failed) process.exit(1); }
main().catch(e=>{console.error(e);process.exit(1)});
