import { readCandlesForApi, upsertDailyCandles, pruneDailyCandles, oneYearCutoff, type CandleTable } from "../lib/data/daily-candles";
import { getSp500CandleUniverse } from "../lib/data/daily-candles";
import { marketCandleAssets } from "../lib/data/market-assets";
import { equityProviderTicker, fetchUnusualWhalesEquityCandles, verifyEquityCandleDatabaseReady } from "../lib/data/unusual-whales-equity-candles";
import { refreshDashboardSnapshot } from "../lib/data/live-dashboard";

const args = new Map<string,string>(); for (let i=2;i<process.argv.length;i++) if (process.argv[i].startsWith("--")) args.set(process.argv[i].slice(2), process.argv[i+1]?.startsWith("--") ? "true" : process.argv[++i] ?? "true");
const group = (args.get("group") ?? "all") as "sp500"|"markets"|"all"; const start = Number(args.get("start-index") ?? 0); const limit = Number(args.get("limit") ?? 9999); const force = args.has("force"); const onlySymbol = args.get("symbol")?.toUpperCase();
type Job = { table:CandleTable; symbol:string; providerSymbol:string; assetGroup?:string };
async function verifyStored(table:CandleTable, symbol:string, client:any) { const rows = await readCandlesForApi(table, symbol, "1Y", client) as any[]; const dates=rows.map(r=>r.trading_date).sort(); const duplicateCount=rows.length-new Set(dates).size; return { rowCount:rows.length, earliest:dates[0]??null, latest:dates.at(-1)??null, rowsWithVolume:rows.filter(r=>r.volume!=null).length, duplicateCount }; }
async function main(){ const db=await verifyEquityCandleDatabaseReady(); if(!db.ok) throw new Error(db.error); const sp500 = group === "markets" ? [] : (await getSp500CandleUniverse(db.supabase)).map(symbol=>({table:"sp500_daily_candles" as const, symbol, providerSymbol:equityProviderTicker(symbol)})); const markets = group === "sp500" ? [] : marketCandleAssets.filter(a=>a.chartAvailable && a.unusualWhalesSymbol).map(a=>({table:"market_daily_candles" as const, symbol:a.symbol, providerSymbol:equityProviderTicker(a.unusualWhalesSymbol!), assetGroup:a.group}));
  const seen=new Set<string>(); let jobs=[...sp500,...markets].filter(j=>{const k=`${j.table}:${j.symbol}`; if(seen.has(k)) return false; seen.add(k); return true;}); if(onlySymbol) jobs=jobs.filter(j=>j.symbol===onlySymbol); jobs=jobs.slice(start,start+limit);
  const results:any[]=[]; let inserted=0;
  for (const job of jobs){ try{ const existing=await verifyStored(job.table, job.symbol, db.supabase); if(!force && existing.rowCount>=240){ const r={symbol:job.symbol, table:job.table, skipped:true, reason:"already_backfilled", ...existing}; results.push(r); console.log(r); continue; } const fetched=await fetchUnusualWhalesEquityCandles(job.symbol, job.providerSymbol); if(!fetched.ok) throw new Error(`${fetched.stage}: ${fetched.error}`); fetched.candles.forEach(c=>(c.assetGroup=(job as any).assetGroup)); const up=await upsertDailyCandles(job.table, fetched.candles, db.supabase); const stored=await verifyStored(job.table, job.symbol, db.supabase); if(!stored.rowCount) throw new Error("Post-upsert verification found zero rows"); inserted+=up.upserted; const r={symbol:job.symbol, table:job.table, providerSymbol:job.providerSymbol, ok:true, rawRows:fetched.rawCount, validRows:fetched.parsedCount, rowsUpserted:up.upserted, ...stored}; results.push(r); console.log(r); }catch(e){ const r={symbol:job.symbol, table:job.table, ok:false, error:(e as Error).message.slice(0,300)}; results.push(r); console.error(r); }}
  const failures=results.filter(r=>r.ok===false); let pruned:any={}; if(inserted>0){ const cutoff=oneYearCutoff(); pruned={cutoff, sp500: await pruneDailyCandles("sp500_daily_candles", cutoff, db.supabase), markets: await pruneDailyCandles("market_daily_candles", cutoff, db.supabase)}; }
  let snapshot:any=null; if(inserted>0 && group !== "markets") snapshot = await refreshDashboardSnapshot("markets:latest");
  console.log(JSON.stringify({group, configured:jobs.length, inserted, failures:failures.length, pruned, snapshotMode:snapshot?.payload?.mode ?? null, results:results.slice(0,50)},null,2)); if(failures.length) process.exit(1); }
main().catch(e=>{ console.error(e); process.exit(1); });
